name: ValidarVariablesEntorno
on:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Se Observa los datos del repositorio
        run:  |
          echo "Repositorio : ${{ github.repository}}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor}}"

