# .github/workflows/hola-mundo.yml

name: Hola Mundo JS

on:
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Crear archivo JS
        run: |
          echo "console.log('Hola Mundo desde GitHub Actions');" > hola.js
          node hola.js
